# Generated by Django 3.2.12 on 2022-09-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_employee_emp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='HighestQualification',
        ),
    ]
